Resources:
  # The federated identity for our user pool to auth with
  SmilyFacesCognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      # Generate a name based on the stage
      IdentityPoolName: sf_${self:custom.stage}_identity_pool
      # Don't allow unauthenticated users
      AllowUnauthenticatedIdentities: false
      # Link to our User Pool
      CognitoIdentityProviders:
        - ClientId:
            Ref: SmilyFacesCognitoUserPoolClient
          ProviderName: 
            Fn::GetAtt: [SmilyFacesCognitoUserPool, ProviderName]

  # transform to map with dynamic keys #
  TransformedRoleMapping:
    Type: Custom::TransformedRoleMapping
    Properties:
      ServiceToken: 
        Fn::GetAtt: [CognitoRoleMappingTransformer, Arn]
      Type: Token
      AmbiguousRoleResolution: AuthenticatedRole
      IdentityProvider: 
        Fn::Join:
          - ':'
          -
            - Fn::GetAtt: [SmilyFacesCognitoUserPool, ProviderName]
            - Ref: SmilyFacesCognitoUserPoolClient
  
  # attach roles to the identity pool #
  SmilyFacesCognitoIdentityPoolRoles:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId:
        Ref: SmilyFacesCognitoIdentityPool
      Roles:
        authenticated:
          Fn::GetAtt: [SmilyFacesCognitoAuthRole, Arn]
      RoleMappings: 
          Fn::GetAtt: [TransformedRoleMapping, RoleMapping]
    
  # IAM role used for authenticated users
  SmilyFacesCognitoAuthRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Federated: 'cognito-identity.amazonaws.com'
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud':
                  Ref: SmilyFacesCognitoIdentityPool
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': authenticated
      Policies:
        - PolicyName: 'CognitoAuthorizedPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'mobileanalytics:PutEvents'
                  - 'cognito-sync:*'
                  - 'cognito-identity:*'
                Resource: '*'
              
              # Allow users to invoke our API
              - Effect: 'Allow'
                Action:
                  - 'execute-api:Invoke'
                Resource:
                  Fn::Join:
                    - ''
                    -
                      - 'arn:aws:execute-api:'
                      - Ref: AWS::Region
                      - ':'
                      - Ref: AWS::AccountId
                      - ':'
                      - Ref: ApiGatewayRestApi
                      - '/*'
              
              # Allow users to upload attachments to their
              # folder inside our S3 bucket
              - Effect: 'Allow'
                Action:
                  - 's3:*'
                Resource:
                  - Fn::Join:
                    - ''
                    -
                      - Fn::GetAtt: [PhotosBucket, Arn]
                      - '/private/'
                      - '$'
                      - '{cognito-identity.amazonaws.com:sub}/*'

# Print out the Id of the Identity Pool that is created
Outputs:
  IdentityPoolId:
    Value:
      Ref: SmilyFacesCognitoIdentityPool        