Resources:
  SmilyFacesCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      # Generate a name based on the stage
      UserPoolName: sf-${self:custom.stage}-user-pool
      # Set email as an alias
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

  SmilyFacesCognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      #Generate an app client name based on the stage
      ClientName: sf-${self:custom.stage}-user-pool-client
      UserPoolId:
        Ref: SmilyFacesCognitoUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false

# Print out the Id of the User Pool that is created
Outputs:
  UserPoolId:
    Value:
      Ref: SmilyFacesCognitoUserPool
  UserPoolClientId:
    Value:
      Ref: SmilyFacesCognitoUserPoolClient