Resources:
  PhotosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      #Generate a name based on the stage
      TableName: ${self:custom.stage}-photos
      AttributeDefinitions:
        - AttributeName: photoId
          AttributeType: S
      KeySchema:
        - AttributeName: photoId
          KeyType: HASH
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
